= Use-Case Model: {project-name}
Alexander Minukow <alexander.minukow@htw-dresden.de>; Mirjam Müller <mirjam.mueller@htw-dresden.de>; Simon Voges <simon.voges@htw-dresden.de> 
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
:imagesdir: ./images
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen
Nachfolgend werden die identifizierten Use Cases (UC) aufgelistet und näher beschrieben. Zur Verbesserung der Gesamtübersicht wird ein Use Case Diagramm abgebildet.

== Identifizierte Use Cases
// Liste aller identifizierten Use Cases (priorisiert)

Die Use Cases wollen wir in folgender Priorität umsetzen und implementieren:

* *UC01*: Antrag stellen
* *UC05*: Antragsverwalter anmelden
* *UC02*: Tagesordnung erstellen 
* *UC06*: Beschlüsse einpflegen
* *UC03*: Tagesordnung abschließen
* *UC04*: Plenumssitzung vertagen 

// Antragsverwalter war niedrigste Priorität, --> geändert da ohne Anmeldung gesamte Applikation nicht sinnvoll --> Diskussionsbedarf ob an zweiter stelle oder nicht!!

Die Priorisierung ergibt sich aus folgenden Faktoren:

* Wichtigkeit für den Kunden
* Sinnvolle Grundfunktionalitäten
* Schwierigkeit der Umsetzung
* Vorhandensein des benötigten Know-how für die Umsetzung.

Da "UC01: Antrag stellen" die Kernfunktionalität der Webanwendung abbildet und es die wichtigste Funktionalität für den Kunden darstellt, ist es unsere höchste Priorität, diesen Use Case als Erstes zu implementieren. +
Ohne "UC05: Antragsverwalter anmelden" kann die Webanwendung nicht sinnvoll verwendet werden, da sonst Authentifizierung als Admin möglich ist. Da es für die Verwaltung der Anträge nötig ist, ist es einer unserer hochpriorisierten Funktionalitäten. +
UC02 und UC06 stellen wichtige Funktionalitäten für unseren Kunden dar, aufgrund des nötigen Know-hows und Komplexität sind sie von der Priorität mittig angesetzt. +
UC03 und UC04 sind nicht zwangsläufig für die Benutzung der Webanwendung nötig, daher sind es unsere am niedrigsten priorisierten Funktionalitäten.

<<<
== Use Case Diagramm

[plantuml, "{diagramsdir}/use-case-diagramm", svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
actor Antragssteller as AS
actor Antragsverwalter as AV
actor Systemadministrator as SA

package Use-Cases {
    usecase "Antrag stellen" as UC1
    usecase "Tagesordnung erstellen" as UC2
    usecase "Beschlüsse einpflegen" as UC6
    usecase "Tagesordnung abschließen" as UC3
    usecase "Plenumssitzung vertagen" as UC4
    usecase "Antragsverwalter anmelden" as UC5
}
AS --> UC1
AV --> UC2
AV --> UC6
AV --> UC3
AV --> UC4
AV --> UC5
SA --> UC5

@enduml
....

//Fügen Sie nachfolgend alle detaillierten Use-Cases per Include ein.
//Dafür sollten Sie pro Use-Case eine Datei anlegen, die auf dem use_case_01.inc.adoc Template basiert.

////
Mit `<<<` wird im PDF ein Seitenumbruch erzeugt.
Zwischen `include::...` und dem darauf folgenden `<<<` muss sich eine Leerzeile befinden. Fehlt diese, werden unter Umständen die erste Überschriften aus der inkludierten Datei nicht korrekt übernommen.
Ein `include` entfernt am Anfang und Ende eine möglich Leerzeile, was in Kombination mit `<<<` zu Fehlern führen kann.
////
<<<
== Use Cases

include::use_case_01.inc.adoc[leveloffset=+1]

<<<
include::use_case_02.inc.adoc[leveloffset=+1]

<<<
include::use_case_03.inc.adoc[leveloffset=+1]

<<<
include::use_case_04.inc.adoc[leveloffset=+1]

<<<
include::use_case_05.inc.adoc[leveloffset=+1]

<<<
include::use_case_06.inc.adoc[leveloffset=+1]

