= Betriebsdokumentation

//Ziel: Administrator beim Einrichten, Konfigurieren und Betreuen des Systems unterstützen

== Systemvoraussetzungen
// Mindestanforderungen für Hardware: CPU, RAM, Festplatte, Netz 
// Softwareanforderungen: Name und Version von Betriebssystem, Datenbank, Webserver, Browser

* PostgreSQL
* WSGI-kompatibler Webserver (Apache, Nginx)
* Betriebssystem (idealerweise NixOS)
* Python 3.9
* Docker
* lokal laufendes Etherpad
* CertBot

Mindestanforderungen der Hardware sind die gleichen wie die vom WSGI-kompatiblen Webserver und die vom Betriebssystem.

== Systemeinrichtung
// Aus welchen Komponenten (EXE, JAR, JS, HTML, CSS, …) besteht die Software? 
// Wie müssen diese installiert (… kopiert, registriert, …) werden? Verzeichnisstruktur?
// Wie müssen die Bestandteile ihres Systems konfiguriert werden? IP-Adressen, Passwörter, Berechtigungen, …

Die Befehle sollen per Terminal eingegeben werden.

1. Alles im Ordner `./src` muss auf den Server bzw. dem dedizierten Speicherort kopiert werden.

2. `cd src`

3. `docker-compose up -d` um die Datenbank und Djangoanwendung zu starten.

4. `docker exec -i abv-tool bash < dbinit.sh` befüllt die Datenbank mit den in `./src/abv/Antragstool/fixtures` festgelegten Default-Daten.

5. `docker exec -it abv-tool python3 abv/manage.py createsuperuser` kreiert einen Nutzer für den internen Bereich im Tool.

6. Danach müssen alle gewünschten DNS-Einträge auf den Server zeigen.


== Systembetreuung
// FAQ für Benutzersupport 
// Fehlerdiagnose, z.B. anhand von Logfile-Einträgen
// Datensicherung und –wiederherstellung
Bei der Installation können automatische Updates aktiviert werden. Außerdem sollte in regelmäßigen Abständen Updates von Python Paketen installiert werden, dies macht man mithilfe des Befehls _docker-compose build_ . Hierbei muss allerdings beachtet werden, dass hierbei keine Kompatibilitätsprobleme auftreten. Ggf. muss in solchen Fällen der Anwendungscode angepasst werden.
