= Projektbericht

== Projektplanung

=== Aufgabenstellung und Auftraggeber


=== Ausgangssituation

=== Projektorganisation
//d.h. Team, Rollen/Verantwortlichkeiten, Kommunikation im Team und zum Auftraggeber, eingesetzte Tools in der Projektarbeit, z.B. für Planung, Kommunikation, Dokumentation

==== Rollenverteilung

Zu Beginn des Projektes hat sich das Team auf folgende Rollenverteilung geeinigt: 


* Göran Heinemann		*Programmierung*/Tester
* Alexander Minukow	    *Analyse*/Entwurf
* Mirjam Müller         *Analyse*/Teamleitung
* Xuan Huy Nguyen		*Entwurf*/Programmierung
* Max Patecky			*Tester*/Technical-Writer
* Marten Petters	    *Teamleitung*
* Simon Voges			*Deployment-Engineer*

Die Rollenverteilung begründetet sich hauptsächlich auf die persönlichen Präferenzen der Teammitglieder in Verbindung mit den verschiedenen Vorkenntnissen und Kompetenzen. 

Nach dem Ende des 3. Semesters verließ Marten Petters das Team, da im Studiengang Wirtschaftsingenieurwesen nur das Modul Software Engineering I Teil des Studiengangs ist. Dadurch ware eine Anpassung der Rollenverteilung notwendig. Im Zuge dessen wurde auch nochmal die generelle Verteilung der Aufgaben geprüft. Neben der Neuorganisation des Projektmanagements wurde auch die Rolle des Deployment-Engineers neu vergeben. 

* Göran Heinemann		*Programmierung/Deployment-Engineer*
* Alexander Minukow	    *Analyse*/Entwurf
* Mirjam Müller         *Teamleitung*/Analyse
* Xuan Huy Nguyen		*Entwurf*/Programmierung
* Max Patecky			*Tester*/Technical-Writer
* Simon Voges			*stellv. Teamleitung*/#Diagramm-Verantwortlicher#

==== Kommunikation und Dokumentation

Zur Kommunikation nutzte das Team einen WhatsApp Gruppenchat sowie einen Discord Server. Über WhatsApp wurden Termine abgestimmt und kurze Infos mitgeteilt. Alles weitere wurde über den Discord Server geteilt. Die Meetings wurden in einem Google Doc dokumentiert. Dazu nutzte das Team eine feste Vorlage, durch die auch der Ablauf eines Teammeetings unterstützt wurde. Die Aufgaben wurden in diesem Google Docs aufgeschrieben und anschließend in das GitHub repository übertragen. 

#Screenshot Vorlage google docs#


=== Techniken/Praktiken
//Techniken/Praktiken: Welche wurden warum eingesetzt und wie genutzt? → „Way of Working“

*Open UP*

*Management Practices*

* Iterative Developement

Das Projekt wird in zweiwöchigen Iterationen organisiert. Dazu trifft sich das Team mindestens einmal in jeder Iteration um alle anstehenden Aufgaben zu besprechen und zu verteilen. Die daraus resultierenden Issues werden in unserem gemeinsamen GitHub Repository eingestellt und den verantwortlichen Personen zugewiesen. Mehrere Iterationen werden den Meilensteinen aus dem OpenUp zugeordnet. Je nach Bedarf werden kurze Besprechungen während der Iteration durchgeführt z. B. um ein Meeting mit dem Coach oder dem StuRa vorzubereiten. Ein Teammitglied wird als Schriftführer benannt, welches dafür zuständig ist alle besprochenen Punkte in einem Protokoll festzuhalten.


* #Risk-Value Lifecycle#
* #Release Planning#

* *Whole Team*
Das Team ist über die gesamte Projektlaufzeit immer mehr zusammengewachsen.Schon von Beginn an war unser Team sehr eigenverantwortlich organisiert. Jeder hat seinen eigenen Verantwortlich- und Kompetenzbereich worin selbstständig Aufgaben erkannt, benannt und im Team besprochen und verteilt werden. Zu Beginn des Projektes führte dies zu einem sehr unterschiedlichen Workload, auch bedingt durch die Rollenverteilung. Im Laufe des Projektes glich sich der workload der einzelnen Teammitglieder immer mehr an. Zum einen war dies bedingt durch eine bessere Aufgabenverteilung bedingt, aber auch das Team ist über die Zeit besser zusammengewachsen. Durch das steigende Zugehörigkeitsgefühl stieg auch die Bereitschaft andere Aufgaben zu übernehmen und nicht nur auf seinem Bereich zu schauen. So glich sich der workload über die Projektlaufzeit immer mehr an, sodass zum Ende des Projektes jeder einen ähnlichen workload hatte. Besonders wichtig war es hierbei, dass auch Aufgaben übernommen wurden, die weniger den eigenen Kompetenzen oder Wünschen entsprachen, aber zum Wohle des Teams bzw. des Projektes übernommen wurden. 

* #Team Change Management#

*Team Change Management*
Am Anfang von SE 1 haben wir Verantwortlichkeiten und Backup Rollen festgelegt, aus diesen Verantwortlichkeiten bilden sich Aufgaben, die selbstständig aber auch in Absprache mit dem Team abzuarbeiten sind. Bei Bedarf kann innerhalb des Teams auch eine Aufgabenumverteilung oder Unterstützung angefragt werden.
Durch das Ausscheiden unseres Projektmanagers nach SE 1, mussten wir Rollen und Verantwortlichkeiten umverteilen, dies geschah unter Berücksichtigung von Kompetenzen und Wünschen der einzelnen Teammitglieder. Die Aufgabensammlung geschieht nach wie vor, wie in SE 1, durch die Verantwortlichen in den jeweiligen Bereichen, jedoch werden Aufgaben nun konkret nach Kompetenzen und nicht mehr nach Rollen bzw. Verantwortlichkeiten verteilt.

* #Project Process Tailoring#



*Technical Practices*

* #Concurrent Testing#
* #Continuous Integration#

* Evolutionary Architecture
Das Architecture Notebook wird schrittweise bearbeitet. Es wird sich hierbei am Projektfortschritt orientiert.

* #Ecolutionary Design#

* Shared Vision
Die erarbeitet Vision mit Zweck und Problembeschreibung wurde in enger Zusammenarbeit mit dem Auftraggeber erarbeitet und mit diesem abgestimmt. Auch nach der finalen Abstimmung wird der Projektfortschritt regelmäßig mit der Vision und dem Auftraggeber abgeglichen und ggf. auf neue oder geänderte Anforderungen abgestimmt. 

* #Test Driven Developement#

* Use Case Driven Developement
Dem gesamtem Projekt liegt das ein Use Case Model zugrunde welches in Zusammenarbeit mit dem Auftraggeber entwickelt wurde. Aus diesem ergeben sich auch die System Wide Requirements wo system-weite funktionale Anforderungen angegeben werden, die nicht als Use Cases ausgedrückt werden können. Auch Anforderungen zur Benutzbarkeit werden hier beschrieben.


*Deployment Practices*

* Docuemtenation and Training
* Production Realease

== Projektdurchführung
// Kurze Beschreibung der Ziele, Aktivitäten und Ergebnisse in den OpenUP-Projektphasen / Iterationen, dabei Berücksichtigung des Zusammenspiels zwischen den einzelnen Rollen sowie Risiken


== Ergebnisdokumentation

=== Ergebnisse

=== Reflexion der Teammitglieder

==== Reflexion von Göran Heinemann
==== Reflexion von Alexander Minukow
==== Reflexion von Mirjam Müller
==== Reflexion von Xuan Huy Nguyen
==== Reflexion von Max Patecky
==== Reflexion von Simon Voges