Mirjam Müller <mirjam.mueller@htw-dresden.de>; Vorname2 Nachname2 <email2@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Antragsdaten

Es erfolgt zu besseren Übersicht eine Auflistung aller Antragsarten mit den jeweiligen Antragsdaten.

=== Antragsdaten - Stammdaten

Diese Antragsdaten sind in jedem Antrag vorhanden und deshalb einmal hier zusammengefasst aufgeführt. 

[%header]
|===
| Bezeichnung | Definition | Format | Gültigkeitsregeln | Aliase

| Antragstitel 
| Thematische Überschrift des Antrages
| String
| Pflichtfeld
| Antragsname

| zuständige Stelle (Auswahl) 
| 
| drop down Menü
| nur Auswahl aus Liste zulässig
| 

| Name 
| Name und Vorname des Antragstellers bzw. Bezeichnungs des Referates
| String
| Pflichtfeld
| Antragsteller

| E-Mail Adresse 
| 
| String
| Emailadresse muss @-Zeichen und . Punkt enthalten; Pflichtfeld
| 

| Antragstext
| Text mit dem Anliegen an den StuRa: "Der StuRa möge beschließen ..."
| String
| 
| Antragsbeschreibung

| Anlagen
| zusätzliche Informationen zu einem Antrag z. B. ein Finanzplan
| keine Einschränkungen auf bestimmte Dateiformate
| #Dateigröße?#
| 

|===


=== Antrag ohne finanzielle Mittel

Alle Anträge, bei denen der StuRa keine Gelder bereitstellen soll und die nicht zu Personalentscheidungen gehören, sollen hier gestellt werden. Dazu gehören zum Beispiel ideelle Unterstützungsanträge oder Anträge auf Änderung einer Ordnung des StuRa oder der Studentinnen- und Studentenschaft.

[%header]
|===
| Bezeichnung  | Format | Gültigkeitsregeln | Aliase

| Begründung zum Antrag
| String
| 
| 

| Vorschlag zum weiteren Verfahren
| String
| 
| 

|===

=== Antrag mit finanziellen Mitteln

Alle Anträge, bei denen der StuRa Geld bereitstellen soll, gehören hier her. Dazu gehören zum Beispiel Anträge auf Ausrichtung einer Veranstaltung, die Übernahme von Fahrt- oder Reisekosten, die Übernahme von Beratungsgebühren oder die Beschaffung von Gegenständen, Software oder anderen Gütern.

[%header]
|===
| Bezeichnung  | Format | Gültigkeitsregeln | Aliase

| Begründung zum Antrag
| String
| #max. Zeichen#
| 

| Kostenposition im Haushaltsplan
| #String#
| Pflichtfeld
| 

| Vorschlag zum weiteren Verfahren
| String
| #max Zeichen#
| 

|===

=== Antrag zu beratendes Mitglied

Jede Person, die im StuRa mitwirken möchte, kann Beratendes Mitglied werden. Dies ist unter anderem die Voraussetzung dafür, Zugriff auf die Ressourcen des StuRa zu erhalten, Mitwirkung finanziell entschädigt zu bekommen oder eine Nichtanrechnung von Semestern nach §20 Abs. 4 SächsHSFG zu erhalten, wenn nicht bereits andere Ämter in der studentischen Interessenvertretung ausgeübt werden. Allgemein ist eine Wahl zum Beratenden Mitglied meist der niedrigschwellige Einstieg in die Mitwirkung beim StuRa.

//Strukturierung
[%header]
|===
| Bezeichnung | Format | Gültigkeitsregeln | Aliase

| *Vorstellung der Person* + 
- Mitgliedschaften in weiteren Organisationen +
- Umfang der Funktionsausübung +
- Bereitschaft zu weiterem Engagement +
- Unterstützungs-bereitschaft 
| String
| #max Zeichen#
| 
|===

=== Antrag zu Stelle/Amt

Wer auf ein konkretes Amt im StuRa kandidieren möchte, kann hier einen Antrag stellen. Eine vorherige Wahl zum Beratenden Mitglied ist nicht notwendig. Es sei auf die Stellenausschreibungen hingewiesen, die der StuRa auf seiner Webseite veröffentlicht.
Dieser Antrag kann nicht verwendet werden, um auf ein Amt der akademischen Selbstverwaltung zu kandideren, wie zum Beispiel dem Senat, dem Fakultätsrat oder einer Studienkommission! Die Adressaten solcher Kandidaturen sind in der Regel die jeweiligen Vorsitzenden der Gremien. Allerding können hier auch Anträge gestellt werden, als Wahlvorschlag des StuRa auf ein solches Amt zu kandidieren. Fragen hierzu können am besten an stura@stura.htw-dresden.de gestellt werden.
Ebenso kann hiermit nicht als Stimmberechtigtes Mitglied im Plenum kandidert werden. Dies ist nur nach vorheriger Wahlausschreibung durch die Wahlleitung der Studentinnen- und Studentenschaft möglich. Kandidaturen für das Plenum des StuRa müssen an die Wahlleiterin der Studentinnen- und Studentenschaft, erreichbar unter wahl@stura.htw-dresden, gerichtet werden.

[%header]
|===
| Bezeichnung | Format | Gültigkeitsregeln | Aliase

| StuRa Mitglied (Ja/Nein)
| boolean
| Auswahlfeld mit Ja/Nein
| 

|*Vorstellung der Person* + 
- Mitgliedschaften in weiteren Organisationen +
- Umfang der Funktionsausübung +
- Bereitschaft zu weiterem Engagement +
- Unterstützungs-bereitschaft 
| String
| 
| 


| *Allgemeine Fragen zum speziellen Amt:*
Wie bewertest du die Ausschreibung für das Amt? +
- Wie bewertest du die Arbeit deiner VorgängerInnen? +
- Welche Themen würdest du in der Amtszeit in den Fordergrund stellen? 
| String
| 
| 

|===

=== Antrag zu Herstellung des Benehmens

Dieses Antragsformular richtet sich vor allem an die Dekan:innen und Studiendekan:innen der HTW. Soll nach §91 SächsHSFG das Benehmen für eine odere mehrere Personen hergestellt werden, die Studiendekan:in oder Mitglied einer Studienkommission werden sollen, kann dies hier beantragt werden.

[%header]
|===
| Bezeichnung  | Format | Gültigkeitsregeln | Aliase

| Begründung zum Antrag
| String
| 
| 

| Vorschlag zum weiteren Verfahren
| String
| 
| 

|===

=== #Antrag zu Veranstaltung#

[%header]
|===
| Bezeichnung  | Format | Gültigkeitsregeln | Aliase

| Begründung zum Antrag
| String
| 
| 

| Vorschlag zum weiteren Verfahren
| String
| 
| 

| Verantwortlichkeit für Nachbereitung
| String
| Pflichtfeld
| 

|===

