= Use-Case Model: {project-name}
Alexander Minukow <alexander.minukow@htw-dresden.de>; Mirjam Müller <mirjam.mueller@htw-dresden.de>; Simon Voges <simon.voges@htw-dresden.de> 
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
<<<<<<< HEAD
:imagesdir: ./images
=======
:imagesdir: images
>>>>>>> parent of e9dd795 (wireframe bilder hinzugefügt)
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen
Nachfolgend werden die identifizierten Use Cases (UC) aufgelistet und näher beschrieben. Zur Verbesserung der Gesamtübersicht wird ein Use Case Diagramm abgebildet.

== Identifizierte Use Cases
// Liste aller identifizierten Use Cases (priorisiert)

Die Use Cases wollen wir in folgender Priorität umsetzen und implementieren:

* *UC01*: Antrag stellen
* *UC02*: Tagesordnung erstellen 
* *UC06*: Beschlüsse einpflegen
* *UC03*: Tagesordnung abschließen
* *UC04*: Plenumssitzung vertagen 
* *UC05*: Antragsverwalter anmelden


== Use Case Diagramm

[plantuml, "{diagramsdir}/use-case-diagramm", svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
actor Antragssteller as AS
actor Antragsverwalter as AV
actor Systemadministrator as SA

package Use-Cases {
    usecase "Antrag stellen" as UC1
    usecase "Tagesordnung erstellen" as UC2
    usecase "Beschlüsse einpflegen" as UC6
    usecase "Tagesordnung abschließen" as UC3
    usecase "Plenumssitzung vertagen" as UC4
    usecase "Antragsverwalter anmelden" as UC5
}
AS --> UC1
AV --> UC2
AV --> UC6
AV --> UC3
AV --> UC4
AV --> UC5
SA --> UC5

@enduml
....

//Fügen Sie nachfolgend alle detaillierten Use-Cases per Include ein.
//Dafür sollten Sie pro Use-Case eine Datei anlegen, die auf dem use_case_01.inc.adoc Template basiert.

////
Mit `<<<` wird im PDF ein Seitenumbruch erzeugt.
Zwischen `include::...` und dem darauf folgenden `<<<` muss sich eine Leerzeile befinden. Fehlt diese, werden unter Umständen die erste Überschriften aus der inkludierten Datei nicht korrekt übernommen.
Ein `include` entfernt am Anfang und Ende eine möglich Leerzeile, was in Kombination mit `<<<` zu Fehlern führen kann.
////

//== Use Cases

<<<
include::use_case_01.inc.adoc[]

<<<
include::use_case_02.inc.adoc[]

<<<
include::use_case_03.inc.adoc[]

<<<
include::use_case_04.inc.adoc[]

<<<
include::use_case_05.inc.adoc[]

<<<
include::use_case_06.inc.adoc[]

<<<
include::wireframes.adoc[]