= Architecture Notebook: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
:imagesdir: ./images
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Nebenbedingungen, Begründungen, wesentliche
Elemente und andere übergreifende Aspekte, die Einfluss auf Entwurf und Implementierung
bezüglich der Realisierung eines in der Vision beschriebenen Antrags- und Beschlussverwaltungstool haben. Die für die Architektur getroffenen Entscheidungen und Ihre
Hintergründe werden hier festgehalten.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!


== Architekturziele und Philosophie
Das Tool soll eine webbasierte Anwendung für den StuRa der HTW Dresden sein. Sie dient zum Stellen von Anträgen, zur Verwaltung dieser Anträge und der Dokumentation von Beschlüssen, sowie der automatischen Erstellung einer standardisierten und übersichtlichen Tagesordnung für die Sitzungen des StuRas. Dabei wird der Großteil der Benutzeroberfläche vom Vorgänger übernommen.

Da die Antragsstellung einen zentralen Aspekt in der Arbeit des StuRas darstellt, soll das Tool selbsterklärend und intuitiv bedienbar sein.

Ziel ist es, dass das Programm 24h am Tag verfügbar ist. Ausnahmen sind die Downtimes des Servers, auf dem die Anwendung laufen soll. Hierbei sollen vorzugsweise die Server des StuRas als Host dienen, da diese bereits 24h am Tag laufen und die Mehrkosten eines Containers deutlich niedriger sind als vergleichsweise die Anmietung eines externen Dienstes.

Desweiteren ist unsere Anstrebung, dass dieses Toll auch letztlich vom StuRa aktiv genutzt wird, einfach zu warten ist und auch zu einem späteren Zeitpunkt bezüglich dessen Funktionalität einfach erweitert werden kann.

//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).


== Annahmen und Abhängigkeiten
//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]
_Annahmen:_

- Das Vorgängertool wird neuentwickelt.
- Jeder Nutzer besitzt eine stabile Verbindung zum HTW-Netz.
- Jeder Nutzer benutzt einen aktuellen Webbrowser.
- Das Framework des Vorgängers wird vom Stakeholder designtechnisch akzeptiert.
- Das Framework des Vorgängers funktioniert problemlos und ist zukunftssicher.
- Jeder Nutzer ist mit der allgemeinen Nutzung eines Computers vertraut.
- Die Server des StuRas laufen zu jeder Zeit stabil.

_Abhängigkeiten:_

- Wir sind darauf angewiesen, dass alle eingesetzten Frameworks zukunftssicher sind.
- Wir sind auf die Uptime der Server des StuRas angewiesen, damit das Tool weiterhin erreichbar bleibt.
- Ein Teil des Teams lernt DJango als Programmiersprache.

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.
*Funktional*

- NFAF-1: Das System muss alle Anträge, deren Anlagen und die generierten Tagesordnungen persistent speichern.
- NFAF-2: Das System soll die Anträge mit dem entsprechenden Beschluss als pdf-Datei exportieren können.
- NFAF-3: Das System muss sicherstellen, dass nur berechtigte Personen die Tagesordnung bearbeiten können.
- NFAF-4: Das System soll den Anträgen automatisch eine semantisch korrekte Antragsnummer zuweisen.

*Effizienz*

- NFAP-1: Das System soll resistent gegen einen Ausfall bei einer hohen Anzahl gleichzeitiger Nutzer sein.
- NFAP-2: Man soll innerhalb von 3 Klicks zur Antragsstellung kommen.

*Wartbarkeit*

- NFAS-1 Das System soll für einen Administrator verständlich dokumentiert sein.
- NFAS-2 Das System soll fähig sein, weitere Schnittstellen zur Funktionserweiterung zu unterstützen (z.B. Mitgliederdatenbank).

== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

- Wir nutzen HTML, CSS und Javascript für das Frontend, da der Vorgänger dies dafür nutzte und und wir in Absprache mit dem StuRa das Frontend weiterverwenden.
- Als Backend nutzen wir eine Kombination aus Django für die funktionalitäten und PostgreSQL als Datenbank zu Speicherung der Daten.
- Die Erstellung eines neuen Datenbankschemas ist wichtig, da die Datenbank des Vorgängers keine einheitliche Form (keine Normalisierung) hat und wir keine Dokumentation vom Vorgänger haben, um die Entscheidungen nachzuvollziehen.

== Architekturmechanismen
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

*1. Sicherheit*

Die Daten sollen so wie sie beschlossen werden, sicher verwahrt sein. Es sollen keine Zugriffe von unberechtigten Personen erfolgen.

*2. Workflow*

Mit der Erstellung einer standardisierten Tagesordnung, kann der Bearbeitungsprozess der Anträge und nach

*3. Persistenz*

Für die Zukunft soll das System, einfach wartbar und auch funktionell erweiterbar sein.

*4. Informationsaustausch*

Nachdem der Prozess der Antragstellung durchgelaufen ist, soll der Antragsteller eine E-Mail mit der Antragsnummer erhalten.

*5. Internationalisierung*

Wir haben vor eine englische Version des Tools bereitzustellen, damit es auch nicht-deutschsprachige Personen mit dem Tool arbeiten können.

*6. Scheduling*

Anträge müssen zu einer gewissen Zeit vor der Plenumssitzung gestellt werden und das Tool soll eine standardtisierte Tagesordnung für Sitzungen der Plena und Refarate ausgeben.

*7. Online-Hilfe*

Sofern wir genügend Zeit übrig haben, wollen wir Online ein Handbuch bereitstellen. Desweiteren werden wir Nutzungshinweise im Tool einfügen.

== Wesentliche Abstraktionen
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]
* *Klasse Antrag:*
- *Finanzantrag:* Enthält alle Informationen zu einem Antrag, mit Mittelanfrage (TOP).
- *nicht finanzieller Antrag:* Enthält alle Informationen zu einem Antrag, ohne Mittelanfrage (ITOP).
* *Klasse Nutzer:*
- *Antragsteller:* Enthält alle Informationen zum Antrag und stellt diesen.
- *Antragverwalter:* Trägt Beschlüsse ein und speichert Tagesordnung.
* *Tagesordnung:* Enthält alle Anträge, die in der Sitzung besprochen werden sollen.
* *Beschluss:* Enthält alle Informationen zum Antrag und wie in der Sitzung darüber abgestimmt wurde.

== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]
Wir nutzen ein MVC-Pattern. Dadurch können wir notwendige Anpassungen schnell und flexibel verwirklichen, da die einzelnen Schichten klar voneinander getrennt sind.

Das MVC-Pattern ist ein Muster zur Unterteilung einer Software in die drei Komponenten Datenmodell (model), Präsentation (view) und Programmsteuerung (controller). Ziel ist die Begünstigung späterer Erweiterungen oder Änderungen und eine Wiederverwendbarkeit der einzelnen Komponenten durch einen flexiblen Programmentwurf.

Die obere Schicht ist die Präsentationsschicht (Front-End, view). Sie wird als normale Website mit mehreren Unterseiten dargestellt. Sie dient zur Darstellung der Sitzungsdaten und hier soll der Antragssteller alle Daten für einen Antrag eingeben.

Die mittlere Schicht ist die Logikschicht(controller). Sie stellt die Verbindung vom Front-End zum Back-End dar. Hier findet man alle Funktionalitäten, die vom Tool erwartet werden, wieder.

Die untere Schicht ist die Datenhaltungsschicht (Back-End,model). Sie enthält die Datenbank und soll alle Anträge und Änderungen an den Anträgen speichern und archivieren.



== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

=== Use Case Modell

<<Use Case Diagramm>>

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.
[plantuml, "{diagramsdir}/c4-model-container", svg]
....
@startuml example-c4-modell-diagram
' source: https://github.com/plantuml-stdlib/C4-PlantUML
' C4 Model
!include <c4/C4_Context.puml>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Images
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

' Diagram title
title \nC4 Model\n

' Diagram syntax
Person(as, Antragsteller, "Stellt Antrag")
Person(av, Antragverwalter, "Verwaltet Anträge")
Person(sa, Systemadmin, "Betreut das System")

System_Boundary(c0, "StuRa Server") {

    System(avbt, "AVB-Tool", "Speichert Anträge und Beschlüsse und lässt bestimmte Nutzer verwalten.")
    System(mail_system, "E-Mail System", "Das interne E-Mailsystem.")
    ContainerDb(db,"Datenbank","Archiv","Speichert alle gestellten und bearbeiteten Anträge, Beschlüsse und Tagesordnungen")

    Rel(avbt,db, "speichert in")
    Rel(as, avbt, "stellt Antrag in")
    Rel(sa, avbt, "Erstellt/Löscht Nutzer")
    Rel(sa, mail_system, Administriert)
    Rel(avbt,mail_system,"sendet Informationen")
    Rel(mail_system,as,"Informiert über Antragsnummer")
    Rel(av,avbt,"nutzt")
}
@enduml

