# Generated by Django 4.2.1 on 2023-05-29 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antragssteller',
            fields=[
                ('astellerID', models.UUIDField(db_column='asteller_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('astellerName', models.TextField(db_column='asteller_name', max_length=50)),
                ('astellerVorname', models.TextField(db_column='asteller_vorname', max_length=50)),
            ],
            options={
                'db_table': 'antragssteller',
            },
        ),
        migrations.CreateModel(
            name='Antragstyp',
            fields=[
                ('typID', models.UUIDField(db_column='typ_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typName', models.TextField(db_column='typ_name', max_length=200)),
            ],
            options={
                'db_table': 'antragstyp',
            },
        ),
        migrations.CreateModel(
            name='Referat',
            fields=[
                ('refID', models.UUIDField(db_column='ref_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refName', models.TextField(db_column='ref_name', max_length=200)),
                ('refZyklus', models.IntegerField(db_column='zyklus')),
            ],
            options={
                'db_table': 'referat',
            },
        ),
        migrations.CreateModel(
            name='Sitzung',
            fields=[
                ('sitzID', models.UUIDField(db_column='sitz_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitzDate', models.DateField(db_column='sitz_date')),
                ('refID', models.ForeignKey(db_column='ref_id', on_delete=django.db.models.deletion.CASCADE, to='Antragstool.referat')),
            ],
            options={
                'db_table': 'sitzung',
            },
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('antragID', models.UUIDField(db_column='antrag_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('antragText', models.TextField(db_column='antrag_text')),
                ('astellerID', models.ForeignKey(db_column='asteller_id', on_delete=django.db.models.deletion.CASCADE, to='Antragstool.antragssteller')),
                ('sitzID', models.ForeignKey(db_column='sitz_id', on_delete=django.db.models.deletion.CASCADE, to='Antragstool.sitzung')),
                ('typID', models.ForeignKey(db_column='typ_id', on_delete=django.db.models.deletion.CASCADE, to='Antragstool.antragstyp')),
            ],
            options={
                'db_table': 'antrag',
            },
        ),
    ]
