# Generated by Django 4.2.1 on 2023-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragstool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antragstyp',
            name='typSlug',
            field=models.TextField(db_column='typ_slug', default=None, max_length=200),
            preserve_default=False,
        ),
    ]
