= Projektplan: {project-name}
Marten Petters <marten.petters@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Briefly describe the content of the project plan.
Der StuRa hat aktuell einen sehr hohen Vewaltungsaufwand mit den Antrags- und Beschlussverwaltungen. Aktuell läuft jeder Arbeitsschritt manuell hab. Das Ziel ist daher die Erstellung eines Tools, welches den Aufwand, insbesondere die Vergabe und Überwachung der Auftragsnummern vereinfacht.

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.

In Software Engineering I einigte sich das Team zu Beginn des Projektes auf folgende Rollenverteilung:

* Alexander Minukow	    *Analyse*/Entwurf
* Göran Heinemann		*Programmierung*/Tester
* Huy Nguyen			*Entwurf*/Programmierung
* Simon Voges			*Deployment-Engineer*
* Max Patecky			*Tester*/Technical-Writer
* Mirjam Müller         *Analyse*/Teamleitung
* Marten Petters	    *Teamleitung*

Grundlage hierfür waren zum Einen die Vorkenntnisse der einzelnen Teammitglieder, welche sich aus Wissen aus dem Studium sowie selbst angeeignetem Wissen bestand. Zum Anderen war die Bereitschaft eine bestimmte Rolle zu übernehmen und sich dafür entsprechendes Wissen anzueignen ausschlaggebend. 

In Software Engineering II verlässt Marten Petters das Team, da im Studiengang Wirtschaftsingeneurwesen nur das Modul Software Engineering I belegt werden kann. Dadurch und durch den Projektfortschritt sind Anpassungen an der Rollenverteilung notwendig. Das Team einigte sich auf folgende neue Rollenverteilung: 

* Alexander Minukow	    *Analyse*/Entwurf
* Göran Heinemann		*Programmierung/Deployment-Engineer*
* Huy Nguyen			*Entwurf*/Programmierung
* Simon Voges			*stellv. Teamleitung*/#Diagramm-Verantwortlicher#
* Max Patecky			*Tester*/Technical-Writer
* Mirjam Müller         *Teamleitung*/Analyse

Neben der Teamleitung war eine größe Änderung die Rolle des Deployment-Engineers. #...#	

In SE I gab es regelmäßige Treffen, die mindestens alle zwei Wochen stattfanden. In SE I wurden die Termine individuell abgestimmt. In SE II einigte sich das Team auf einen regelmäßig wiederkehrenden Termin, immer am Dienstag in der geraden Woche stattfindet. Zur Terminplanung und für kurze Absprachen oder Nachrichten hat das Team einen WhatsApp Gruppenchat. Weiterhin nutzen wir Discord für unsere Meetings und zum Austausch von Informationen. Unsere Meetings dokumentieren wir in einem Google Doc, was allen Mitgliedern zur Verfügung steht. 

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

Das Team nutzt Open Up für die Organisation des Projektes. In allen Meetings wird Protokoll geführt, ein Teammitglied ist dafür verantwortlich, das restliche Team kontrolliert dieses. Alle Änderungen und Vorhaben werden umgehend mit dem Kunden abgeklärt und durch diesen bestätigt. Unser Kunden Kontakt ist Theresa Minister.


== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Kennenlerenen und Rollenverteilung
* Kundenwünsche kennenleren
| 12.12.2022/ 21.12.2022
| 15

| I2
|
* Datenerfassung (Use-Cases, Vision, Glossar)
* Projektdokumentation
| 04.01.2023/13.01.2023
| 16

|I3
|
* Fertigstellung Prototyp
* Fertigstellung Dokumentation
|16.01.2023/ 27.01.2023
|17
|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Am Ende von SE2 soll die Software fertig gestellt sein und auf den Servern des StuRa laufen. Ein Teammitglied ist ebenso StuRa-Mitglied und verantwortlich für Betreuung des Systems.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

Die Zusammenarbeit des Teams war grundlegend gut. Durch Verbesserung der Kommunikation und regelmäßige Rückfragen konnte das entfallen von Daten verbessert werden.
