= Projektplan: {project-name}
Marten Petters <marten.petters@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== #Einführung#
//Briefly describe the content of the project plan.
Der StuRa hat aktuell einen sehr hohen Verwaltungsaufwand mit den Antrags- und Beschlussverwaltungen. Aktuell läuft jeder Arbeitsschritt manuell hab. Das Ziel ist daher die Erstellung eines Tools, welches den Aufwand, insbesondere die Vergabe und Überwachung der Auftragsnummern vereinfacht.

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.

In Software Engineering I einigte sich das Team zu Beginn des Projektes auf folgende Rollenverteilung:

* Alexander Minukow	    *Analyse*/Entwurf
* Göran Heinemann		*Programmierung*/Tester
* Huy Nguyen			*Entwurf*/Programmierung
* Simon Voges			*Deployment-Engineer*
* Max Patecky			*Tester*/Technical-Writer
* Mirjam Müller         *Analyse*/Teamleitung
* Marten Petters	    *Teamleitung*

Grundlage hierfür waren zum Einen die Vorkenntnisse der einzelnen Teammitglieder, welche sich aus Wissen aus dem Studium sowie selbst angeeignetem Wissen bestand. Zum Anderen war die Bereitschaft eine bestimmte Rolle zu übernehmen und sich dafür entsprechendes Wissen anzueignen ausschlaggebend. 

In Software Engineering II verlässt Marten Petters das Team, da im Studiengang Wirtschaftsingeneurwesen nur das Modul Software Engineering I belegt werden kann. Dadurch und durch den Projektfortschritt sind Anpassungen an der Rollenverteilung notwendig. Das Team einigte sich auf folgende neue Rollenverteilung: 

* Alexander Minukow	    *Analyse*/Entwurf
* Göran Heinemann		*Programmierung/Deployment-Engineer*
* Huy Nguyen			*Entwurf*/Programmierung
* Simon Voges			*stellv. Teamleitung*/#Diagramm-Verantwortlicher#
* Max Patecky			*Tester*/Technical-Writer
* Mirjam Müller         *Teamleitung*/Analyse

Neben der Teamleitung war eine größere Änderung die Rolle des Deployment-Engineers. #...#	

In SE I gab es regelmäßige Treffen, die mindestens alle zwei Wochen stattfanden. In SE I wurden die Termine individuell abgestimmt. In SE II einigte sich das Team auf einen regelmäßig wiederkehrenden Termin, immer am Dienstag in der geraden Woche stattfindet. Zur Terminplanung und für kurze Absprachen oder Nachrichten hat das Team einen WhatsApp Gruppenchat. Weiterhin nutzen wir Discord für unsere Meetings und zum Austausch von Informationen. Unsere Meetings dokumentieren wir in einem Google Doc, was allen Mitgliedern zur Verfügung steht. 

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

*Open UP*

*Management Practices*

* Iterative Developement

Das Projekt wird in zweiwöchigen Iterationen organisiert. Dazu trifft sich das Team mindestens einmal in jeder Iteration um alle anstehenden Aufgaben zu besprechen und zu verteilen. Die daraus resultierenden Issues werden in unserem gemeinsamen GitGub Respository eingestellt und den verantwortlichen Personen zugewiesen. Mehrere Iterationen werden den Meilensteinen aus dem OpenUp zugeordnet. Am Ende von SE I soll der Meilenstein Elaboration Phase abgeschlossen sein. Je nach Bedarf werden kurze Besprechungen während der Iteration durchgeführt z. B. um ein Meeting mit dem Coach oder dem StuRa vorzubereiten. Ein Teammitglied wird als Schriftführer benannt, welches dafür zuständig ist alle besprochenen Punkte in einem Protokoll festzuhalten.


* #Risk-Value Lifecycle#
* #Release Planning#
* #Whole Team#
* #Team Change Management#
* #Project Process Tailoring#

*Technical Practices*

* #Concurrent Testing#
* #Continuous Integration#

* Evolutionary Architecture
Das Architecture Notebook wird schrittweise bearbeitet. Es wird sich hierbei am Projektfortschritt orientiert.

* #Ecolutionary Design#

* Shared Vision
Die erarbeitet Vision mit Zweck und Problembeschreibung wurde in enger Zusammenarbeit mit dem Auftraggeber erarbeitet und mit diesem abgestimmt. Auch nach der finalen Abstimmung wird der Projektfortschritt regelmäßig mit der Vision und dem Auftraggeber abgeglichen und ggf. auf neue oder geänderte Anforderungen abgestimmt. 

* #Test Driven Developement#

* Use Case Driven Developement
Dem gesamtem Projekt liegt das ein Use Case Model zugrunde welches in Zusammenarbeit mit dem Auftraggeber entwickelt wurde. Aus diesem ergeben sich auch die System Wide Requirements wo system-weite funktionale Anforderungen angegeben werden, die nicht als Use Cases ausgedrückt werden können. Auch Anforderungen zur Benutzbarkeit werden hier beschrieben.


*Deployment Practices*

* Docuemtenation and Training
* Production Realease


== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

//Phasen --> Meilensteine müssen hier rein aus Open UP eigene Meilensteine möglich (Zeitpunkt!)

[%header, cols="1,3a,2"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone

| I1
|
* Kennenlernen des Teams
* Rollenverteilung 
* GitHub einrichten
* Kundenwünsche kennenlernen und verstehen
* Vision erarbeiten
* *Meilenstein: Inception Phase abgeschlossen*
| 12.12.2022/21.12.2022

| I2
|
* Use-Cases beschreiben
* Vision beenden
* system wide requirements bestimmen
* Deployment
* Projektdokumentation
| 04.01.2023/13.01.2023

|I3
|
* Analyse beenden
* Architecture Notebook
* Implementierung und Präsentation Prototyp
* Termin mit Auftraggeber
* Fertigstellung Dokumentation und Abgabe Beleg
* *Meilenstein: Elaboration Phase abgeschlossen*
|16.01.2023/27.01.2023

|I4
|
* Auswertung Beleg
* Nacharbeiten SE I
* Implementierung UC 5
* #Deployment vorbereiten#
|03.04.2023/16.04.2023

|I5
|
* Implementierung UC 1
* Umstrukturierung des Frontends
* Deployment finalisieren
|17.04.2023/30.04.2023

|I6
|
* 
* 
* 
* 
|01.05.2023/14.05.2023

|I7
|
* 
* 
* 
* 
|15.05.2023/28.05.2023

|I8
|
* 
* 
* 
* *Meilenstein: Construction Phase abgeschlossen*
|29.05.2023/11.06.2023

|I9
|
* System ist vom Kunden einsetzbar 
* *Meilenstein: Transition Phase abgeschlossen*
* *Präsentation des Systems beim StuRa und Freigabe abholen
* *Belegabgabe*
|12.06.2023/23.06.2023

|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Am Ende von SE2 soll die Software fertig gestellt sein und auf den Servern des StuRa laufen. Ein Teammitglied ist ebenso StuRa-Mitglied und verantwortlich für Betreuung des Systems.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

Die Zusammenarbeit des Teams war grundlegend gut. Durch Verbesserung der Kommunikation und regelmäßige Rückfragen konnte das entfallen von Daten verbessert werden.

* Meetings vorbereiten und alle wichtigen Punkte vorher aufschreiben und diese dann im Meeting abarbeiten

* festen wiederkehrenden Termin für Meetings festlegen, dass spart sehr viel Zeit

* (Die wichtigsten) Aufgaben wirklich nach Kenntnissen und Fähigkeiten verteilen, weniger nach Kapazitäten und im Sinne von "Ja kann ich schon machen"

* Issues sollten kleinteiliger erstellt werden. Das wurde in SE II so umgesetzt und funktionierte insgesamt besser