version: "3"
services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: abv
      POSTGRES_USER: abv
      POSTGRES_PASSWORD: abv
    volumes:
      - pg_data:/var/lib/postgresql

  mailcatcher:
    restart: on-failure
    image: gitlab.goeranh.de/goeranh/mailcatcher:latest
    environment:
    - MDNS_HOSTNAME=mailcatcher
    ports:
    - "1080:1080"
    - "1025:1025"

volumes:
  pg_data:
