version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abv
      POSTGRES_PASSWORD: abv
      POSTGRES_DB: abv
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
