version: "3"
services:

  abv:
    build: .
    container_name: 'abv-tool'
    ports:
      - 8020:8020
    environment:
      - DJANGO_SECRET_KEY=testkey-plz-change
      - DB_NAME=${DB_NAME:-Antragstool}
      - DB_USER=${DB_USER:-abv}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_PASSWORD=${DB_PASSWORD:-abv}
      - EMAIL_HOST=${EMAIL_HOST:-mailcatcher}
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - ETHERPAD_API_KEY="36432eb264ecb4c515c2d1f84b5469c7"

  db:
    image: postgres
    container_name: 'postgres-db'
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    environment:
      - POSTGRES_DB=${DB_NAME:-Antragstool}
      - POSTGRES_USER=${DB_USER:-abv}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-abv}
    volumes:
      - pg_data:/var/lib/postgresql

  mailcatcher:
    restart: on-failure
    image: gitlab.goeranh.de/goeranh/mailcatcher:latest
    container_name: 'mailcatcher'
    environment:
    - MDNS_HOSTNAME=mailcatcher
    ports:
    - "1080:1080"
    - "${EMAIL_PORT}:${EMAIL_PORT}"

volumes:
  pg_data:
