version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abv
      POSTGRES_PASSWORD: abv
      POSTGRES_DB: abv
    volumes:
      - pg_data:/var/lib/postgresql
  #abv:
  #  build: .
  #  restart: unless-stopped
  #  ports:
  #    - 8020:8020
  #  depends_on:
  #    - db
  #  environment:
  #    DJANGO_SUPERUSER_USERNAME: admin
  #    DJANGO_SUPERUSER_USERNAME: admin
  #    DJANGO_SUPERUSER_EMAIL: admin@test.com

volumes:
  pg_data:
